---
title: "Home Credit Default Risk"
author: "Singh, Gurjeet"
date: "October 23, 2018"
output: ↨
      ioslides_presentation:
          widescreen: true
          fig_width: 10
          fig_height: 5
          fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

```


```{r 0_load_library, echo=FALSE}
##-------------------
# Load Libraries
##-------------------
options(knitr.kable.NA = '')
library(tidyverse)
library(dplyr)
library(lubridate)
options(scipen = 999)
```


```{r}
##-------------------
# Import Data
##-------------------

#       #train_df <- read_csv("Data_application_train.csv")
#       #save.image(file = "work_space_20181026.RData")
# 
# train_df <- read_csv("Data_application_train.csv")
# train_bureau_df <- read_csv("Data_bureau.csv")
# train_bureau_bal_df <- read_csv("Data_bureau_balance.csv")
# train_Cred_Crd_bal_df <- read_csv("Data_credit_card_balance.csv")
# train_inst_pmts_df <- read_csv("Data_installments_payments.csv")
# train_POS_Cash_bal_df <- read_csv("Data_POS_CASH_balance.csv")
# train_prev_appl_df <- read_csv("Data_previous_application.csv")
# 
# save.image(file = "work_space_20181026_PM_04_00.RData")


```

```{r}
##save.image(file = "work_space_20181027_AM_10_53.RData")
##load("work_space_20181027_AM_10_53.RData")

```


```{r}
train_df
```


```{r}
##------------------------------------------
#  Selected variables per domain knowledge
##------------------------------------------
Grp_app_train_df <- train_df %>% 
                          select (SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY,
                                  CNT_CHILDREN, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, NAME_INCOME_TYPE,
                                  NAME_EDUCATION_TYPE, NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, REGION_POPULATION_RELATIVE, DAYS_BIRTH,
                                  DAYS_EMPLOYED,
                                  DAYS_REGISTRATION, REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY,
                                  REG_CITY_NOT_WORK_CITY,
                                  LIVE_CITY_NOT_WORK_CITY, EXT_SOURCE_1, EXT_SOURCE_1, EXT_SOURCE_3,
                                  FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5,
                                  FLAG_DOCUMENT_6, 
                                  FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9, FLAG_DOCUMENT_10, FLAG_DOCUMENT_11,
                                  FLAG_DOCUMENT_12,
                                  FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15, FLAG_DOCUMENT_16, FLAG_DOCUMENT_17,
                                  FLAG_DOCUMENT_18, 
                                  FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21)
```



```{r}
Grp_app_train_df
```

```{r}
train_bureau_df %>% 
  arrange(SK_ID_CURR)
```


```{r}
##------------------------------------------
# Condense the Bureau data by grouping
##------------------------------------------
Grp_bureau_df <-  train_bureau_df %>% 
                  filter(CREDIT_ACTIVE == 'Active'& !is.na(AMT_CREDIT_SUM)) %>% 
                      mutate(IMP_AMT_CREDIT_SUM_DEBT = replace_na(AMT_CREDIT_SUM_DEBT,0)) %>% 
                      mutate(IMP_AMT_CREDIT_SUM_LIMIT = AMT_CREDIT_SUM - IMP_AMT_CREDIT_SUM_DEBT) %>% 
                      group_by(SK_ID_CURR) %>% 
                      summarize(Total_AMT_CREDIT_SUM = sum(AMT_CREDIT_SUM),
                                Total_IMP_AMT_CREDIT_SUM_DEBT = sum(IMP_AMT_CREDIT_SUM_DEBT),
                                Total_IMP_AMT_CREDIT_SUM_LIMIT = sum(IMP_AMT_CREDIT_SUM_LIMIT))
```


```{r}
train_Cred_Crd_bal_df %>% 
  arrange(SK_ID_CURR)
```

```{r}
##------------------------------------------
# Filter and Condense the Credit card Balance by grouping
##------------------------------------------ 
Grp_Cred_crd_bal_df <- train_Cred_Crd_bal_df %>% 
                          filter(NAME_CONTRACT_STATUS == c("Active")) %>% 
                          mutate(IMP_AMT_BALANCE = replace_na(AMT_BALANCE,0)) %>% 
                          mutate(IMP_AMT_CREDIT_LIMIT_ACTUAL = replace_na(AMT_CREDIT_LIMIT_ACTUAL,0)) %>% 
                          mutate(IMP_AMT_DRAWINGS_ATM_CURRENT = replace_na(AMT_DRAWINGS_ATM_CURRENT,0)) %>% 
                          mutate(IMP_AMT_DRAWINGS_CURRENT = replace_na(AMT_DRAWINGS_CURRENT,0)) %>% 
                          mutate(IMP_AMT_DRAWINGS_OTHER_CURRENT = replace_na(AMT_DRAWINGS_OTHER_CURRENT,0)) %>% 
                          mutate(IMP_AMT_DRAWINGS_POS_CURRENT = replace_na(AMT_DRAWINGS_POS_CURRENT,0)) %>% 
                          mutate(IMP_SK_DPD = replace_na(SK_DPD,0)) %>% 
                          mutate(IMP_SK_DPD_DEF = replace_na(SK_DPD_DEF,0)) %>% 
                                           group_by(SK_ID_CURR) %>% 
                                          summarize(Total_IMP_AMT_BALANCE = sum(IMP_AMT_BALANCE),
                                                    Total_IMP_AMT_CREDIT_LIMIT_ACTUAL = sum(IMP_AMT_CREDIT_LIMIT_ACTUAL),
                                                    Total_IMP_AMT_DRAWINGS_ATM_CURRENT = sum(IMP_AMT_DRAWINGS_ATM_CURRENT),
                                                    Total_IMP_AMT_DRAWINGS_CURRENT = sum(IMP_AMT_DRAWINGS_CURRENT),
                                                    Total_IMP_AMT_DRAWINGS_OTHER_CURRENT = sum(IMP_AMT_DRAWINGS_OTHER_CURRENT),
                                                    Total_IMP_AMT_DRAWINGS_POS_CURRENT = sum(IMP_AMT_DRAWINGS_POS_CURRENT),
                                                    Total_IMP_SK_DPD = mean(IMP_SK_DPD),
                                                    Total_IMP_SK_DPD_DEF = mean(IMP_SK_DPD_DEF),
                                                    Total_prev_months = n())
```



```{r}
train_inst_pmts_df
```

```{r}
train_inst_pmts_df %>% 
  arrange(SK_ID_CURR,SK_ID_PREV )
```




```{r}
##------------------------------------------
# Filter and Condense the POS Cash Balance by grouping
##------------------------------------------

Grp_POS_Cash_bal_df <- train_POS_Cash_bal_df %>% 
                        filter(NAME_CONTRACT_STATUS == c("Active")) %>% 
                        group_by(SK_ID_CURR) %>% 
                        summarize(Total_SK_DPD = mean(SK_DPD),
                                    Total_SK_DPD_DEF = mean(SK_DPD_DEF),
                                    Total_prev_months = n())

```


```{r}
##------------------------------------------
# NOT helpful to include in the final population
##------------------------------------------
train_prev_appl_df %>% 
  arrange(SK_ID_CURR)
```


```{r}
##------------------------------------------
# NOT helpful to include in the final population - DO NOT USE
##------------------------------------------

train_bureau_bal_df
```


Other work
```{r}
train_POS_Cash_bal_df
#View(train_POS_Cash_bal_df)
```



```{r}
str(train_POS_Cash_bal_df)


train_POS_Cash_bal_df %>% 
    filter(SK_DPD == 4231 | SK_DPD_DEF == 3595)

train_POS_Cash_bal_df %>% 
    filter(NAME_CONTRACT_STATUS == c("Signed","Approved","Returned to the store","Demand", "Canceled", "XNA", "Amortized debt"))

train_POS_Cash_bal_df %>% 
    filter(SK_DPD == 4231 | SK_DPD_DEF == 3595)

train_POS_Cash_bal_df %>% 
    distinct(NAME_CONTRACT_STATUS)

train_POS_Cash_bal_df %>% 
    filter(NAME_CONTRACT_STATUS == c("Active") & SK_ID_CURR == c(100003)) %>% 
  arrange(SK_ID_CURR)
```


```{r}
left_join(Grp_app_train_df, Grp_bureau_df, by = "SK_ID_CURR") %>% 
    left_join(Grp_Cred_crd_bal_df, by = "SK_ID_CURR") %>% 
    left_join(Grp_POS_Cash_bal_df, by = "SK_ID_CURR") 
```




```{r}
left_join(train_df, Grp_bureau_df, by = "SK_ID_CURR") %>% 
    left_join(Grp_Cred_crd_bal_df, by = "SK_ID_CURR") %>% 
    left_join(Grp_POS_Cash_bal_df, by = "SK_ID_CURR") 
```































